export enum ErrorCodes {
  IsUrl = 22,
  Max = 23,
  Min = 24,
  IsEmail = 25,
  Length = 26,
  MaxLength = 27,
  MinLength = 28,
  IsPhoneNumber = 29,
  IsNumberString = 30,
  IsBoolean = 31,
  IsNumber = 32,
  IsInt = 33,
  IsString = 34,
  IsArray = 35,
  IsObject = 36,
  IsPassword = 37,

  IncorrectRequestType = 100,
  NotValidParameters = 101,
  NotEnoughPermissions = 102,
  Unauthorized = 103,
  UnexpectedJSON = 104,
  UrlNotFound = 105,
  CredentialsNotValid = 106,
  OperationFailed = 107,
  DataNotFound = 108,
  IsAlreadyExist = 109,
  UserNotFound = 110,
  AnActiveSubscriptionAlreadyExists = 111,
  SendEmailError = 112,
  EmailNotVerified = 113,
  VerificationCodeNotValid = 114,
  WrongToken = 115,
  OpenAiError = 116,
  OpenAiKeyNotFound = 117,
  FileLoadError = 118,
  GenerationImageError = 119,
  FailedWriteFile = 120,
  userAccessDenied = 121,
  PasswordIsSameAsOld = 122,
  WaitingApproving = 123,
  TooManyLoginAttempts = 124,
  EmailAlreadyConfirmed = 125,
}

export const ErrorDescriptionsArray = {
  [ErrorCodes.NotEnoughPermissions]: "You Don't Have Permissions",
  [ErrorCodes.TooManyLoginAttempts]:
    "It's too many login attempts, please try later!",
  [ErrorCodes.PasswordIsSameAsOld]: 'Password is tha same',
  [ErrorCodes.WaitingApproving]: 'Waiting approving registration',
  [ErrorCodes.UrlNotFound]: 'Url not found',
  [ErrorCodes.UnexpectedJSON]: 'Unexpected JSON',
  [ErrorCodes.Unauthorized]: 'Unauthorized',
  [ErrorCodes.NotValidParameters]: 'Not Valid Parameters',
  [ErrorCodes.CredentialsNotValid]: 'Credentials Not Valid',
  [ErrorCodes.OperationFailed]: 'Operation Failed',
  [ErrorCodes.DataNotFound]: 'Data Not Found',
  [ErrorCodes.IsAlreadyExist]: 'Is Already Exist',
  [ErrorCodes.UserNotFound]: 'User Not Found',
  [ErrorCodes.AnActiveSubscriptionAlreadyExists]:
    'An Active Subscription Already Exists',
  [ErrorCodes.SendEmailError]: 'Send Email Error',
  [ErrorCodes.EmailNotVerified]: 'Email Not Verified',
  [ErrorCodes.VerificationCodeNotValid]: 'Verification Code Not Valid',
  [ErrorCodes.WrongToken]: 'Wrong Token',
  [ErrorCodes.OpenAiError]: 'OpenAi Error',
  [ErrorCodes.OpenAiKeyNotFound]: 'OpenAi Key Not Found',
  [ErrorCodes.EmailAlreadyConfirmed]: 'Email Already Confirmed',
};
